### ISSUE TITLE
Hang in RS_Line::draw when opening dxf file

### ISSUE THREAD

**Issue by mycae** [LibreCAD/LibreCAD#1089]
Librecad hangs when opening a DXF file I have, particularly when running the RS_Line::draw() routine. I'm running 2.1.2 from Debian stretch ( 2.1.2-1+b1). 

Specifically, in my file (which I can share privately),  when opening the dxf the program hangs in the below loop (rs_line.cpp), as length is very large and total never reaches it:
```

84         RS_Vector curP{pStart+direction*total};
685         for (int j=0; total<length; j=(j+1)%pat->num) {
686 
687         // line segment (otherwise space segment)
688                 double const t2=total+fabs(ds[j]);
689                 RS_Vector const& p3=curP+dp[j];
690         if (ds[j]>0.0 && t2 > 0.0) {
691             // drop the whole pattern segment line, for ds[i]<0:
692             // trim end points of pattern segment line to line
693                         RS_Vector const& p1 =(total > -0.5)?curP:pStart;
694                         RS_Vector const& p2 =(t2 < length+0.5)?p3:pEnd;
695             painter->drawLine(p1,p2);
696         }
```
```
(gdb) info locals
t2 = 1310637897.8169217
p3 = @0x7fffffffa4f0: {x = 1969.3615593626603, y = 1310638740.816921, z = 0, valid = true}
j = 0
curP = {x = 1969.3615593626603, y = 1310638733.2629642, z = 0, valid = true}
patternSegmentLength = 3
total = 1310637897.8169217
viewportRect = {_minP = {x = -1494.8223371730753, y = -807.2950248931669, z = 0, valid = true}, _maxP = {x = -300.93532852825098, y = -168.2812164566038, z = 0, valid = true}}
endPoints = {vector = std::vector of length 2, capacity 2 = {{x = -2.0000000000000031, y = -88, z = 0, valid = true}, {x = -2.000000000000004, y = -90, z = 0, valid = true}}, tangent = false}
ec = {<RS_Entity> = {<RS_Undoable> = {<RS_Flags> = {_vptr.RS_Flags = 0x555555e85648 <vtable for RS_EntityContainer+16>, flags = 2}, cycle = 0x0}, parent = 0x0, minV = {x = 10000000000, y = 10000000000, z = 0, 
      valid = true}, maxV = {x = -10000000000, y = -10000000000, z = 0, valid = true}, layer = 0x0, id = 44205, pen = {<RS_Flags> = {_vptr.RS_Flags = 0x555555e82888 <vtable for RS_Pen+16>, flags = 0}, 
      lineType = RS2::SolidLine, width = RS2::Width00, screenWidth = 0, color = {<QColor> = {cspec = QColor::Rgb, ct = {argb = {alpha = 65535, red = 0, green = 0, blue = 0, pad = 0}, ahsv = {alpha = 65535, 
              hue = 0, saturation = 0, value = 0, pad = 0}, acmyk = {alpha = 65535, cyan = 0, magenta = 0, yellow = 0, black = 0}, ahsl = {alpha = 65535, hue = 0, saturation = 0, lightness = 0, pad = 0}, 
            array = {65535, 0, 0, 0, 0}}}, <RS_Flags> = {_vptr.RS_Flags = 0x555555e82868 <vtable for RS_Color+16>, flags = 0}, <No data fields>}}, updateEnabled = true, varList = std::map with 0 elements}, 
  entities = {<QListSpecialMethods<RS_Entity*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, 
                  _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x555556b52300}, d = 0x555556b52300}}, subContainer = 0x0, static autoUpdateBorders = false, entIdx = -1, 
  autoDelete = true}
pStart = {x = 1969.3615593626603, y = 843, z = 0, valid = true}
pEnd = {x = 1575, y = 8.880232858974633e+17, z = 0, valid = true}
direction = {x = -4.4408920985006257e-16, y = 1, z = 0, valid = true}
length = 8.880232858974624e+17
pat = 0x555555eafd00 <RS_LineTypePattern::patternDashLineTiny>
pen = {<RS_Flags> = {_vptr.RS_Flags = 0x555555e82888 <vtable for RS_Pen+16>, flags = 0}, lineType = RS2::SolidLine, width = RS2::Width00, screenWidth = 0, color = {<QColor> = {cspec = QColor::Rgb, ct = {
        argb = {alpha = 65535, red = 65535, green = 65535, blue = 65535, pad = 0}, ahsv = {alpha = 65535, hue = 65535, saturation = 65535, value = 65535, pad = 0}, acmyk = {alpha = 65535, cyan = 65535, 
          magenta = 65535, yellow = 65535, black = 0}, ahsl = {alpha = 65535, hue = 65535, saturation = 65535, lightness = 65535, pad = 0}, array = {65535, 65535, 65535, 65535, 0}}}, <RS_Flags> = {
      _vptr.RS_Flags = 0x555555e82868 <vtable for RS_Color+16>, flags = 0}, <No data fields>}}

```
Note that the length variable is >1e17, however the end and start points when entering the function in the debugger seemed sane.

As a hack. I've attached a suggested patch to circumvent this by checking the size of length and bailing out 

- as its still compiling, I've not tested this. Nor have I worked out why length is very large.

Interestingly, when I disable the construction setting on the layer, the problem goes away and I can view my file normally.  I can also manually set in the debugger length to, say, 100, and then program continues (only one line in the drawing)

Edit : stack trace below
```
#5  0x000055f42818618e in RS_Line::draw (this=<optimized out>, painter=0x7ffc1f5fc2b0, view=<optimized out>, patternOffset=<optimized out>) at lib/engine/rs_line.cpp:695
#6  0x000055f4282116e9 in RS_GraphicView::drawEntity (this=0x55f42b60be40, painter=0x7ffc1f5fc2b0, e=0x55f42b6adfe0, patternOffset=@0x7ffc1f5fbfe0: -8.880232858974624e+17) at lib/gui/rs_graphicview.cpp:1152
#7  0x000055f42820cf78 in RS_GraphicView::drawEntity (this=<optimized out>, painter=<optimized out>, e=<optimized out>) at lib/gui/rs_graphicview.cpp:1093
#8  0x000055f42815d3c2 in RS_EntityContainer::draw (this=<optimized out>, painter=0x7ffc1f5fc2b0, view=0x55f42b60be40) at lib/engine/rs_entitycontainer.cpp:1770
#9  0x000055f4282116e9 in RS_GraphicView::drawEntity (this=0x55f42b60be40, painter=0x7ffc1f5fc2b0, e=0x55f42b606960, patternOffset=@0x7ffc1f5fc1f0: 0) at lib/gui/rs_graphicview.cpp:1152
#10 0x000055f42820cf78 in RS_GraphicView::drawEntity (this=<optimized out>, painter=<optimized out>, e=<optimized out>) at lib/gui/rs_graphicview.cpp:1093
#11 0x000055f428210ad9 in RS_GraphicView::drawLayer2 (this=0x55f42b60be40, painter=0x7ffc1f5fc2b0) at lib/gui/rs_graphicview.cpp:929
#12 0x000055f4282ef67b in QG_GraphicView::paintEvent (this=0x55f42b60be40) at ui/qg_graphicview.cpp:924
#13 0x00007f4649fc1118 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x000055f4282f16ea in QG_GraphicView::event (this=0x55f42b60be40, event=<optimized out>) at ui/qg_graphicview.cpp:382
#15 0x00007f4649f79b8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007f4649f81351 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007f4649694d30 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007f4649fb9eea in QWidgetPrivate::sendPaintEvent(QRegion const&) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007f4649fba54e in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007f4649fbb25c in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007f4649fba0b4 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007f4649fbb25c in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007f4649fba0b4 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007f4649fbb25c in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007f4649fba0b4 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007f4649fbb25c in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007f4649fba0b4 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007f4649fbb25c in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007f4649fba0b4 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007f4649f89f6f in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#31 0x00007f4649f8a127 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#32 0x00007f4649fa8e8f in QWidgetPrivate::syncBackingStore() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#33 0x00007f4649fc11e8 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#34 0x00007f464a0c02cb in QMainWindow::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#35 0x00007f4649f79b8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#36 0x00007f4649f81351 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#37 0x00007f4649694d30 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#38 0x00007f4649f8a945 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#39 0x00007f4649f8b605 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#40 0x00007f4649fab8d8 in QWidget::repaint(QRect const&) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#41 0x00007f464a10b596 in QStatusBar::hideOrShow() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#42 0x00007f464a10b64a in QStatusBar::showMessage(QString const&, int) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#43 0x000055f4283baeae in QC_ApplicationWindow::slotFileOpen (this=this@entry=0x7ffc1f5ff670, fileName=..., type=<optimized out>) at main/qc_applicationwindow.cpp:1516
#44 0x000055f4283bdbc9 in QC_ApplicationWindow::slotFileOpen (this=0x7ffc1f5ff670) at main/qc_applicationwindow.cpp:1330
#45 0x000055f4283e9cc9 in QC_ApplicationWindow::qt_static_metacall (_o=0x7ffc1f5ff670, _c=<optimized out>, _id=<optimized out>, _a=0x7ffc1f5fe290)
    at ../../generated/librecad/moc/moc_qc_applicationwindow.cpp:373
#46 0x00007f46496c08b9 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#47 0x00007f4649f731c2 in QAction::triggered(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#48 0x00007f4649f75bb0 in QAction::activate(QAction::ActionEvent) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#49 0x00007f464a0e4aea in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#50 0x00007f464a0ec164 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
---Type <return> to continue, or q <return> to quit---
#51 0x00007f464a0ed0f6 in QMenu::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#52 0x00007f4649fc1118 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#53 0x00007f464a0ef423 in QMenu::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#54 0x00007f4649f79b8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#55 0x00007f4649f8220d in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#56 0x00007f4649694d30 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#57 0x00007f4649f808bd in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#58 0x00007f4649fdba26 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#59 0x00007f4649fde003 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#60 0x00007f4649f79b8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#61 0x00007f4649f81351 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#62 0x00007f4649694d30 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#63 0x00007f46499deb03 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#64 0x00007f46499e0675 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#65 0x00007f46499be60b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#66 0x00007f464189c360 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#67 0x00007f46468aa7f7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#68 0x00007f46468aaa60 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#69 0x00007f46468aab0c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#70 0x00007f46496e91cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#71 0x00007f4649692d1a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#72 0x00007f464969b46c in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#73 0x000055f42811c094 in main (argc=<optimized out>, argv=<optimized out>) at main/main.cpp:312

```

**Comment by mycae** [comment]
OK, github wont let me upload patches (unsupported filetype). here it is:
```
diff -r c813af237309 rs_line.cpp
--- a/rs_line.cpp	Thu Apr 25 21:28:47 2019 +0100
+++ b/rs_line.cpp	Thu Apr 25 21:40:23 2019 +0100
@@ -645,6 +645,10 @@
         return;
     }
 //    patternOffset = remainder(patternOffset - length-0.5*pat->totalLength,pat->totalLength)+0.5*pat->totalLength;
+    const float MAX_LENGTH=1e9;
+    if(length > MAX_LENGTH)
+	    return;
+
     if(length<=RS_TOLERANCE){
         painter->drawLine(pStart,pEnd);
         return; //avoid division by zero
```

**Comment by lordofbikes** [comment]
There are a couple of similar cases collected in #915.
Most, if not all, are solved in latest code.
So you can try to build latest code and see if it works or send your file to me, then I can check if it works with latest version.

**Comment by mycae** [comment]
Ive finished compiling the latest git head, and yes the problem does appear to be solved - sorry for the noise!

**Comment by lordofbikes** [comment]
No reason to feel sorry, you're welcome!
And many thanks for testing this.
